### ISSUE TITLE
System.TypeLoadException: Method 'AppendIdentityWhereCondition' in type 'FirebirdSql.EntityFrameworkCore.Firebird.Update.Internal.FbUpdateSqlGenerator' from assembly 'FirebirdSql.EntityFrameworkCore.Firebird, Version=8.5.2.0, Culture=neutral, PublicKeyToken=7a73ef09980c56c9' does not have an implementation.

### ISSUE THREAD

**Issue by Makarov628** [FirebirdSQL/NETProvider#1010]
We tried to use net6.0 and EF Core 5.0.9 with this Firebird Provider
and we got this exception

```
System.TypeLoadException: Method 'AppendIdentityWhereCondition' in type 'FirebirdSql.EntityFrameworkCore.Firebird.Update.Internal.FbUpdateSqlGenerator' from assembly 'FirebirdSql.EntityFrameworkCore.Firebird, Version=8.5.2.0, Culture=neutral, PublicKeyToken=7a73ef09980c56c9' does not have an implementation.
   at Microsoft.EntityFrameworkCore.FbServiceCollectionExtensions.<>c.<AddEntityFrameworkFirebird>b__0_3(ServiceCollectionMap b)
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.TryAddProviderSpecificServices(Action`1 serviceMap)
   at Microsoft.EntityFrameworkCore.FbServiceCollectionExtensions.AddEntityFrameworkFirebird(IServiceCollection serviceCollection)
   at FirebirdSql.EntityFrameworkCore.Firebird.Infrastructure.Internal.FbOptionsExtension.ApplyServices(IServiceCollection services)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.ApplyServices(IDbContextOptions options, ServiceCollection services)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<GetOrAdd>g__BuildServiceProvider|4_0(IDbContextOptions options, ConcurrentDictionary`2 configurations)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.GetOrAdd(IDbContextOptions options, Boolean providerRequired)
   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.CheckState()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
   at System.Linq.Queryable.Where[TSource](IQueryable`1 source, Expression`1 predicate)```

**Comment by cincuranet** [comment]
I don't think EFCore 5 and .NET 6 is a supported scenario. You should use .NET 5 or wait for provider for EF Core 6 (#1003). Also 8.5.2.0 is not up-to-date version.
