### ISSUE TITLE
System.TypeLoadException: Method 'AppendIdentityWhereCondition'  does not have an implementation

### ISSUE THREAD

**Issue by xtephan** [FirebirdSQL/NETProvider#1014]
After migrating to dotnet 6, the following exception is being thrown

```
System.TypeLoadException: Method 'AppendIdentityWhereCondition' in type 'FirebirdSql.EntityFrameworkCore.Firebird.Update.Internal.FbUpdateSqlGenerator' from assembly 'FirebirdSql.EntityFrameworkCore.Firebird, Version=8.5.4.0, Culture=neutral, PublicKeyToken=7a73ef09980c56c9' does not have an implementation.
   at Microsoft.EntityFrameworkCore.FbServiceCollectionExtensions.<>c.<AddEntityFrameworkFirebird>b__0_3(ServiceCollectionMap b)
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.TryAddProviderSpecificServices(Action`1 serviceMap)
   at Microsoft.EntityFrameworkCore.FbServiceCollectionExtensions.AddEntityFrameworkFirebird(IServiceCollection serviceCollection)
   at FirebirdSql.EntityFrameworkCore.Firebird.Infrastructure.Internal.FbOptionsExtension.ApplyServices(IServiceCollection services)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.ApplyServices(IDbContextOptions options, ServiceCollection services)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<GetOrAdd>g__BuildServiceProvider|4_0(IDbContextOptions options, ConcurrentDictionary`2 configurations)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.GetOrAdd(IDbContextOptions options, Boolean providerRequired)
   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.CheckState()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
   at System.Linq.Queryable.Where[TSource](IQueryable`1 source, Expression`1 predicate)
```

Seems to be the same exception as descrobed here: https://github.com/FirebirdSQL/NETProvider/issues/1010 ,however, we are pretty sure we are using efcore 6

**Comment by cincuranet** [comment]
_FirebirdSql.EntityFrameworkCore.Firebird_ version 8.5.4.0 does not support EF Core 6.
