### ISSUE TITLE
FbConnection.CreateDatabase fails with a letter outside the scope of a-z eg. ö (on embedded firebird)

### ISSUE THREAD

**Issue by Rand-Random** [FirebirdSQL/NETProvider#1019]
I have have the following code

```C#
using System.Text;
using FirebirdSql.Data.FirebirdClient;

//this line causes, the creation of the database to work
//the difference is that will FirebirdSql.Data.Common.Encoding2 to be ANSI while System.Text.Encoding.Default to be UTF8
//without this line both are UTF8
//Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);

Directory.CreateDirectory("Föö");
var dbPath = Path.GetFullPath("Föö\\MyFooDatabase.fdb");

//go up to solution dir
var fbClientDll = Path.GetFullPath("..\\..\\..\\..\\Fb4xEmbedded\\fbclient.dll");
var conString = GetEmbeddedConnectionString(fbClientDll, dbPath);

FbConnection.CreateDatabase(conString, 32768, false, true);

static string GetEmbeddedConnectionString(string fbPath, string dbPath)
{
    var stringBuilder = new FbConnectionStringBuilder
    {
        Database = dbPath,
        ClientLibrary = fbPath,
        ServerType = FbServerType.Embedded,
        UserID = "sysdba",
        Password = "sysdba",
    };

    return stringBuilder.ToString();
}
```

I also created a github repository for you to simply download and run.
https://github.com/Rand-Random/FbEmbeddedCreateDataBase

This code will fail with the error message:

> FirebirdSql.Data.FirebirdClient.FbException
>   HResult=0x80004005
>   Message=I/O error during "CreateFile (create)" operation for file "C:\USERS\xxx\SOURCE\REPOS\CONSOLEAPP92\CONSOLEAPP92\BIN\DEBUG\NET6.0\FÃ¶Ã¶\MYFOODATABASE.FDB"
> Error while trying to create file
>   Source=FirebirdSql.Data.FirebirdClient
>   StackTrace:
>    at FirebirdSql.Data.FirebirdClient.FbConnection.CreateDatabase(String connectionString, Int32 pageSize, Boolean forcedWrites, Boolean overwrite)
>    at Program.<Main>$(String[] args) in C:\Users\xxx\source\repos\ConsoleApp92\ConsoleApp92\Program.cs:line 18
> 
>   This exception was originally thrown at this call stack:
>     FirebirdSql.Data.Client.Native.FesDatabase.ProcessStatusVector(System.IntPtr[])
>     FirebirdSql.Data.Client.Native.FesDatabase.CreateDatabase(FirebirdSql.Data.Common.DatabaseParameterBufferBase, string, byte[])
>     FirebirdSql.Data.FirebirdClient.FbConnectionInternal.CreateDatabase(int, bool, bool)
>     FirebirdSql.Data.FirebirdClient.FbConnection.CreateDatabase(string, int, bool, bool)
> 
> Inner Exception 1:
> IscException: I/O error during "CreateFile (create)" operation for file "C:\USERS\xxx\SOURCE\REPOS\CONSOLEAPP92\CONSOLEAPP92\BIN\DEBUG\NET6.0\FÃ¶Ã¶\MYFOODATABASE.FDB"
> Error while trying to create file

It only will fail with `Embedded Server` and you need to use `.net 5` or `.net 6`, those .net versions that have `Encoding.Default` defined as `UTF8` and not `ANSI` as .Net Framework did.

Firebird is Version 4.0.1.2692.

**Comment by Rand-Random** [comment]
Wasn't sure if it is a valid solution or not.
Calling `Encoding.RegisterProvider(CodePagesEncodingProvider.Instance)` doesn't only influence the creation of the database but everything else aswell, and it seems I kind of destroy the purpose of `Encoding2`, don't I?

Also in the life-time of my Application it is possible that I work with an embedded server and a real server and `Encoding2.Default` would than also be different for the real server and not only the embedded server.

**Comment by cincuranet** [comment]
> Calling Encoding.RegisterProvider(CodePagesEncodingProvider.Instance) doesn't only influence the creation of the database but everything else aswell, and it seems I kind of destroy the purpose of Encoding2, don't I?

Nope. Without it the `Encoding2`, simply uses `Encoding.Default` which is _UTF8_ on .NET Core/.NET 5 and later.

> Also in the life-time of my Application it is possible that I work with an embedded server and a real server and Encoding2.Default would than also be different for the real server and not only the embedded server.

If you use Firebird server 3+, almost everything is explicitly UTF8 encoded, so that's not affected.

**Comment by Rand-Random** [comment]
Wouldn't the desired encoding be `UTF8`?
Both scenarios in my application embedded or not are Firebird 4.
Doesn't the embedded server handle `UTF8`? Should I better post the issue on the firebird github?

> almost everything is explicitly UTF8 encoded
Ah, okay, it neither uses `Encoding.Default` nor uses `Encoding2.Default` but instead "simply" `Encoding.UTF8`.
Good one concern less.

**Comment by Rand-Random** [comment]
FYI 

I also tried to move a successfully created database to a folder with an `ö` and than connect to it with the embedded firebird server, and it gives the same result.

Can also be fixed by calling `Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);`

> FirebirdSql.Data.FirebirdClient.FbException
>   HResult=0x80004005
>   Message=I/O error during "CreateFile (open)" operation for file "C:\USERS\xxx\SOURCE\REPOS\CONSOLEAPP92\CONSOLEAPP92\BIN\DEBUG\NET6.0\FÃ¶Ã¶\MYFOODATABASE.FDB"
> Error while trying to open file
>   Source=FirebirdSql.Data.FirebirdClient
>   StackTrace:
>    at FirebirdSql.Data.FirebirdClient.FbConnectionInternal.Connect()
>    at FirebirdSql.Data.FirebirdClient.FbConnection.Open()
>    at Program.<Main>$(String[] args) in C:\Users\xxx\source\repos\ConsoleApp92\ConsoleApp92\Program.cs:line 26
> 
>   This exception was originally thrown at this call stack:
>     FirebirdSql.Data.Client.Native.FesDatabase.ProcessStatusVector(System.IntPtr[])
>     FirebirdSql.Data.Client.Native.FesDatabase.Attach(FirebirdSql.Data.Common.DatabaseParameterBufferBase, string, byte[])
>     FirebirdSql.Data.FirebirdClient.FbConnectionInternal.Connect()
> 
> Inner Exception 1:
> IscException: I/O error during "CreateFile (open)" operation for file "C:\USERS\xxx\SOURCE\REPOS\CONSOLEAPP92\CONSOLEAPP92\BIN\DEBUG\NET6.0\FÃ¶Ã¶\MYFOODATABASE.FDB"
> Error while trying to open file

**Comment by AlexPeshkoff** [comment]
On 1/14/22 16:52, Jiri Cincura ↹ wrote:
>
>     Doesn't the embedded server handle UTF8? Should I better post the
>     issue on the firebird github?
>
> For the filesystem operations it is still using ANSI (at least was 
> using in FB3). Maybe it can be changed in FB5.
>

To make engine accept file names and related info in UTF8 add 
isc_dpb_utf8_filename parameter to DPB.

**Comment by Rand-Random** [comment]
> To make engine accept file names and related info in UTF8 add isc_dpb_utf8_filename parameter to DPB.

Saw the usage of `dpb.Append(IscCodes.isc_dpb_utf8_filename, 0);` in `FirebirdSql.Data.Client.Managed.Version13.GdsDatabase` in method `SendCreateToBuffer` when I debuged the routine while using the non-embedded firebird version, and gave this line a shot for the embedded version.

Therefor I added this line to `FirebirdSql.Data.Client.Native.FesDatabase` in method `CreateDatabase` and it seems to work.
Is it missing?

![image](https://user-images.githubusercontent.com/9868626/149540451-0e0c3c74-0ada-434a-896a-b43f5a11024a.png)

**Comment by cincuranet** [comment]
@AlexPeshkoff The `isc_dpb_utf8_filename` is about strings passed, isn't it? The I/O subsystem calls will still be in ANSI. Or can Firebird running on i.e. Czech system, with Czech locale, now, use Japanese characters in path?

**Comment by AlexPeshkoff** [comment]
On 1/17/22 14:45, Jiri Cincura ↹ wrote:
>
> @AlexPeshkoff <https://github.com/AlexPeshkoff> The 
> |isc_dpb_utf8_filename| is about strings passed, isn't it?
>

Yes, certainly.

> The I/O subsystem calls will still be in ANSI.
>

To be precise - in system charset.

> Or can Firebird running on i.e. Czech system, with Czech locale, now, 
> use Japanese characters in path?
>

That depends upon availability of Japanese characters in system charset. 
When utf8 is used (default for linux) any characters (including 
Japanese) may be used. Even with Czech locale selected.

What about windows - no idea why firebird does not use unicode support 
on it instead ansi.

**Comment by cincuranet** [comment]
OK, so at least for Linux it's worth doing this in embedded too.

The original implementation might have assumed Windows only.

@Rand-Random I'll tackle this together with #1020.

**Comment by Rand-Random** [comment]
Sorry, if I caused one heck of a confusion with my issue.

**Comment by asfernandes** [comment]
Can anyone test this? https://github.com/FirebirdSQL/firebird/issues/7101#issuecomment-1013310914

It does not require code changes, just creation of file.

**Comment by cincuranet** [comment]
@asfernandes I wouldn't say this is safe, because you'd have to modify the .NET loader's manifest (that's the native part that loads and executes .NET code) and who knows what and when breaks with this change. Also it would require manual steps, hardly developer friendly.

**Comment by asfernandes** [comment]
If there is a thing that changes a specific thing (process code page) and it may break things, then I would go away from that platform if I can. :)

It changes things before process starts. And it change things in a way similar as if the OS is configured with that ANSI code page.

It also seems to be possible automated with `mt` as explained.

There is Firebird server executable that can benefit from this.

.NET also have individual executable files for applications in embedded.

For Java (at least old versions) with "centralized" java/javaw executables that may be problematic for embedded. New versions allow one to create its own java tree for their applications.

But I'm sure the easier solution is to wait years and years complaining Firebird did not implement the thing. :)

**Comment by asfernandes** [comment]
I did myself a test using isql. It worked.

Surely there may be situations that this does not work specially with UDFs not expecting this or applications in the case of embedded.

But the less thing that worries me are platforms. They should be ready for this as they should work with multi byte code pages already.

And if a developer wants to allow databases with unicode characters, why not expect they cannot code applications that works in this condition?

Sure, everything must be tested.

**Comment by cincuranet** [comment]
Great. Thanks for letting me know.
