### ISSUE TITLE
Foreign key longer than 31.  Question or Issue?

### ISSUE THREAD

**Issue by PhilPJL** [FirebirdSQL/NETProvider#1039]
I'm using EF 6.4.4 and EntityFramework.Firebird 8.5.4
I have databases on Firebird 3.
I have manually created code first classes to represent the db.  Works perfectly.

e.g. 

```
    [Table("Profile")]
    public class Profile
    {
        [Key]
        [Column("ID")]
        public long Id { get; set; }

        [Column("RECORD_ID")]
        public long RecordId { get; set; }

        [ForeignKey("RecordId")]
        public virtual RawRecord RawRecord { get; set; }

        [Column("XZ_VALUES")]
        public byte[] Values { get; set; }

        [Column("UNITS")]
        [MaxLength(6)]
        public string Units { get; set; }
    }
```

```
    public class TvlAltContext : DbContext
    {
        private static DbConnection GetConnection(string nameOrConnectionString)
        {
            return new FbConnectionFactory().CreateConnection(nameOrConnectionString);
        }

        public TvlAltContext(string nameOrConnectionString = "TvlAlt") : base(GetConnection(nameOrConnectionString), true)
        {
            Database.SetInitializer<TvlAltContext>(null);

            Configuration.LazyLoadingEnabled = false;
            Configuration.ProxyCreationEnabled = false;
        }

        public DbSet<Waveform> Waveforms { get; set; }
        public DbSet<RawRecord> RawRecords { get; set; }
        public DbSet<Profile> Profiles { get; set; }
        public DbSet<IntervalRecord> IntervalRecords { get; set; }
    }
```

Now the problem.  Backup and restore to Firebird 4.  Nothing works because I get errors like:

_The name 'FK_RawRecord_IntervalRecord_INTERVAL_ID' is longer than Firebird's 31 characters limit for object names._

```
   at EntityFramework.Firebird.FbMigrationSqlGenerator.CheckName(String name)
   at EntityFramework.Firebird.FbMigrationSqlGenerator.<Generate>d__9.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at EntityFramework.Firebird.FbMigrationSqlGenerator.Generate(IEnumerable`1 migrationOperations, String providerManifestToken)
   at System.Data.Entity.Migrations.DbMigrator.GenerateStatements(IList`1 operations, String migrationId)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteOperations(String migrationId, VersionedModel targetModel, IEnumerable`1 operations, IEnumerable`1 systemOperations, Boolean downgrading, Boolean auto)
   at System.Data.Entity.Migrations.DbMigrator.AutoMigrate(String migrationId, VersionedModel sourceModel, VersionedModel targetModel, Boolean downgrading)
   at System.Data.Entity.Migrations.DbMigrator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
   at System.Data.Entity.Migrations.DbMigrator.UpdateInternal(String targetMigration)
   at System.Data.Entity.Migrations.DbMigrator.<>c__DisplayClass42_0.<Update>b__0()
   at System.Data.Entity.Migrations.DbMigrator.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
   at System.Data.Entity.Migrations.DbMigrator.Update(String targetMigration)
   at System.Data.Entity.Internal.DatabaseCreator.CreateDatabase(InternalContext internalContext, Func`3 createMigrator, ObjectContext objectContext)
   at System.Data.Entity.Internal.InternalContext.CreateDatabase(ObjectContext objectContext, DatabaseExistenceState existenceState)
   at System.Data.Entity.Database.Create(DatabaseExistenceState existenceState)
   at System.Data.Entity.CreateDatabaseIfNotExists`1.InitializeDatabase(TContext context)
   at System.Data.Entity.Internal.InternalContext.<>c__DisplayClass66_0`1.<CreateInitializationAction>b__0()
   at System.Data.Entity.Internal.InternalContext.PerformInitializationAction(Action action)
   at System.Data.Entity.Internal.InternalContext.PerformDatabaseInitialization()
   at System.Data.Entity.Internal.LazyInternalContext.<>c.<InitializeDatabase>b__58_0(InternalContext c)
   at System.Data.Entity.Internal.RetryAction`1.PerformAction(TInput input)
   at System.Data.Entity.Internal.LazyInternalContext.InitializeDatabaseAction(Action`1 action)
   at System.Data.Entity.Internal.LazyInternalContext.InitializeDatabase()
   at System.Data.Entity.Internal.InternalContext.Initialize()
   at System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   at System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   at System.Data.Entity.Internal.Linq.InternalSet`1.get_InternalContext()
   at System.Data.Entity.Infrastructure.DbQuery`1.System.Linq.IQueryable.get_Provider()
   at System.Linq.Queryable.Take[TSource](IQueryable`1 source, Int32 count)
   at UserQuery
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```
I'm hoping this is solvable.  Help appreciated.

**Comment by PhilPJL** [comment]
Ok, my bad.  newly restored dbs didn't have an alias so code first migrations was trying to create dbs - new to Firebird. 
31 character limit is not good.

**Comment by mrotteveel** [comment]
The maximum length of object names was increased to 63 in Firebird 4.0, so if this error also occurs against Firebird 4.0, that is a bug. @PhilPJL can you confirm if this was with Firebird 4.0 or 3.0?

**Comment by PhilPJL** [comment]
Yes definitely FB4.  Firebird-4.0.1.2692-0-x64.

The scenario is:
Create EF code first model as above.
Reference EF model from LinqPAD.
I restored an FB 3 db to FB 4 (tvlalt).
Configured new connection in LinqPAD like "database=localhost:tvlalt;user=tvlalt;password=*****"
LinqPAD shows the tables
![image](https://user-images.githubusercontent.com/271656/163125424-d1008161-e15d-4c25-a386-c454b0f6acb9.png)
because I guess it's only reading the model at that point.

When I tried to retrieve data, got that error because EF can't see the db an tries to create it.

Changing connection string to "database=localhost:d:\data\tvlalt.fdb;user=tvlalt;password=*****" fixes the issue.

**Comment by asfernandes** [comment]
Firebird 4 has configuration option to limit length of names - MaxIdentifierByteLength and MaxIdentifierCharLength.

So double check if you have them not configured for lower values.

**Comment by PhilPJL** [comment]
It's a clean install of FB4.  I haven't changed anything.

**Comment by PhilPJL** [comment]
The code from FbMigrationSqlGenerator

```
	static string CheckName(string name)
	{
		const int LengthLimit = 31;
		if (name.Length > LengthLimit)
			throw new ArgumentOutOfRangeException($"The name '{name}' is longer than Firebird's {LengthLimit} characters limit for object names.");
		return name;
	}
```

**Comment by lweberprb** [comment]
The 8.5.4 provider is not FB4 aware. You'll have to use 9.0.0 preview

**Comment by cincuranet** [comment]
`EntityFramework.Firebird` is for EF 6 and it is in "maintenance" mode. And it used FB 3 as a last version for which it received updates.

For EF Core provider the support for longer identifiers is planned as part of #931.
