### ISSUE TITLE
DateTime <> Timestamp issue on Entity Framework Core

### ISSUE THREAD

**Issue by MatejSpin** [FirebirdSQL/NETProvider#1049]
Hi,

I have an issue with DateTime (.NET 6) and TIMESTAMP conversion using the EF Core 9.0.1 provider on Firebird 3 server.  
On certain (otherwise same model) databases/systems, it works, but on some, it does not. I get the following error:

 FirebirdSql.Data.FirebirdClient.FbException (0x80004005): arithmetic exception, numeric overflow, or string truncation
string right truncation

I normally set the DateTime property and try to update/insert into the database.

**Here is the generated SQL statement:**
Failed executing DbCommand (1ms) [Parameters=[@p0='2022-06-14T19:02:00.9343040' (DbType = DateTime), @p1='2022-05-21T22:10:00.0000000' (Nullable = true) (DbType = DateTime),  @p2='2022-06-14T19:01:53.1493664' (DbType = DateTime))], CommandType='"Text"', CommandTimeout='0']
INSERT INTO "BET" ("CREATEDDATE", "SELECTIONDATE",  "MODIFIEDDATE")
VALUES (@p0, @p1, @p2)
RETURNING "ID";

Model config:
 entity.Property(e => e.Modifieddate).HasColumnName("MODIFIEDDATE").HasColumnType("timestamp");
 entity.Property(e => e.CreatedDate).HasColumnName("CREATEDDATE").HasColumnType("timestamp");
 entity.Property(e => e.SelectionDate).HasColumnName("SELECTIONDATE").HasColumnType("timestamp");

I tried with and without HasColumnType... All are of type timestamp on database.

Any clue?

**Comment by MatejSpin** [comment]
heres the call stack:

 ---> FirebirdSql.Data.Common.IscException: arithmetic exception, numeric overflow, or string truncation
string right truncation
   at FirebirdSql.Data.Client.Managed.Version10.GdsStatement.WriteRawParameter(IXdrWriter xdr, DbField field)
   at FirebirdSql.Data.Client.Managed.Version13.GdsStatement.WriteParameters()
   at FirebirdSql.Data.Client.Managed.Version10.GdsStatement.GetParameterDataAsync(IDescriptorFiller descriptorFiller, Int32 index, CancellationToken cancellationToken)
   at FirebirdSql.Data.Client.Managed.Version10.GdsStatement.SendExecuteToBufferAsync(Int32 timeout, IDescriptorFiller descriptorFiller, CancellationToken cancellationToken)
   at FirebirdSql.Data.Client.Managed.Version12.GdsStatement.ExecuteAsync(Int32 timeout, IDescriptorFiller descriptorFiller, CancellationToken cancellationToken)
   at FirebirdSql.Data.FirebirdClient.FbCommand.ExecuteCommandAsync(CommandBehavior behavior, Boolean returnsSet, CancellationToken cancellationToken)
   at FirebirdSql.Data.FirebirdClient.FbCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at FirebirdSql.Data.FirebirdClient.FbCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at FirebirdSql.Data.FirebirdClient.FbCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)

**Comment by MatejSpin** [comment]
Well found the issue...
The application was setting the current thread culture to a different one than systems like so:
CultureInfo en = new CultureInfo("en-US");
Thread.CurrentThread.CurrentCulture = en;

If the given application created the database then everything was fine, but if saving to an existing one then the errors occurred.

**Comment by cincuranet** [comment]
That's still weird. The locale should not affect this. Could you maybe create a small sample app so I can check?

**Comment by MatejSpin** [comment]
The issue appears to be when we receive this kind of datetime format in JSON:
"TimeStampUtc": "2022-06-28T08:06:56.189261Z",
This is parsed to UTC datetime..

Will try to provide an example.

**Comment by cincuranet** [comment]
Closing for inactivity.
