### ISSUE TITLE
.NET 7 EF core support

### ISSUE THREAD

**Issue by Igor-ZA** [FirebirdSQL/NETProvider#1082]
Hi,

I just tried creating a test app using .NET 6 + EF 6 core + FirebirdSql.EFCore.Firebird 9.1.0, which works fine.

When updating to  .NET 7+ EF 7  I get one of these exceptions depending on which combination of packages I have
with Microsoft.EntityFrameworkCore.Relational 7:

System.MissingMethodException: Method not found: 'System.Collections.Generic.IList`1<Microsoft.EntityFrameworkCore.Metadata.Conventions.IModelInitializedConvention> Microsoft.EntityFrameworkCore.Metadata.Conventions.ConventionSet.get_ModelInitializedConventions()'.
   at FirebirdSql.EntityFrameworkCore.Firebird.Metadata.Conventions.FbConventionSetBuilder.CreateConventionSet()
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.RuntimeConventionSetBuilder.CreateConventionSet()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, ModelCreationDependencies modelCreationDependencies, Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel(Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()

Known issue?

**Comment by cincuranet** [comment]
Yes. Support for EF Core 7 is not done yet.

**Comment by cincuranet** [comment]
Duplicates #1083.
