### ISSUE TITLE
Scaffold-DbContext Error   - Unable to find expected assembly attribute [DesignTimeProviderServices]

### ISSUE THREAD

**Issue by Nevega** [FirebirdSQL/NETProvider#1160]
Hello Trying 
to Scaffolding BDfirst 
Server version  - WI-V6.3.8.27089 Firebird 2.5

`Scaffold-DbContext "database=****;data source=localhost;user=SYSDBA;password=masterkey" FirebirdSql.Data.FirebirdClient -OutputDir DisModels`

getting error

> PM> Scaffold-DbContext "database=C:\Dista_Data\BD\rmc-2.fdb;data source=localhost;user=SYSDBA;password=masterkey" FirebirdSql.Data.FirebirdClient -OutputDir DisModels
Build started...
Build succeeded.
System.InvalidOperationException: Unable to find expected assembly attribute [DesignTimeProviderServices] in provider assembly 'FirebirdSql.Data.FirebirdClient'. This attribute is required to identify the class which acts as the design-time service provider factory for the provider.
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.ConfigureProviderServices(String provider, IServiceCollection services, Boolean throwOnError)
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.CreateServiceCollection(String provider)
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.Build(String provider)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String outputContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluralize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluralize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
**Unable to find expected assembly attribute [DesignTimeProviderServices] in provider assembly 'FirebirdSql.Data.FirebirdClient'. This attribute is required to identify the class which acts as the design-time service provider factory for the provider.**

**Comment by gilsonjoanelo** [comment]
I'm using Google Translate. Are the web.config settings in accordance with these settings? I remember that I updated the web.config and included this item and also added a system.data item. Follow my web.config, it may help you.

`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    <section name="entityFramework"
      type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"
      requirePermission="false"/>
  </configSections>
   <system.web>
    <globalization culture="pt-BR" uiCulture="pt-BR"/>
    
    <httpRuntime maxRequestLength="21480"/>
    <compilation/>
    <authentication mode="Windows"/>
    <pages controlRenderingCompatibilityVersion="4.0"/>
   </system.web>
  <entityFramework>
    <defaultConnectionFactory type="EntityFramework.Firebird.FbConnectionFactory, EntityFramework.Firebird"/>
    <contexts>
      <context type="DataCempro.Persistencia.Contexto.DataCemproContext,DataCempro.Persistencia.DataCempro" disableDatabaseInitialization="true"/>
    </contexts>
    <providers>
      <provider invariantName="FirebirdSql.Data.FirebirdClient" type="EntityFramework.Firebird.FbProviderServices, EntityFramework.Firebird"/>
      <provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer"/>
    </providers>
  </entityFramework>
  <system.data>
    <DbProviderFactories>
      <remove invariant="FirebirdSql.Data.FirebirdClient"/>
      <add name="FirebirdClient Data Provider" invariant="FirebirdSql.Data.FirebirdClient" description=".NET Framework Data Provider for Firebird"
        type="FirebirdSql.Data.FirebirdClient.FirebirdClientFactory, FirebirdSql.Data.FirebirdClient"/>
    </DbProviderFactories>
  </system.data>
</configuration>
`
