### ISSUE TITLE
error invalid time zone region

### ISSUE THREAD

**Issue by rioda78** [FirebirdSQL/NETProvider#1207]
environment 
asp core 9
entityframeworkcore.firebird 12.0.0-beta1
project aspnet core blazor with identity default

when im try execute database update, it get error "Invalid time zone region: .21.5440". you can see detail error below

```
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (33ms) [Parameters=[], CommandType='Text', CommandTimeout='0']
      EXECUTE BLOCK
      AS
      BEGIN
        BEGIN
                EXECUTE STATEMENT
                        'CREATE TABLE "__EFMigrationsLock" (
                                "Id" INT NOT NULL CONSTRAINT "PK___EFMigrationsLock" PRIMARY KEY,
                                "Timestamp" TIMESTAMP NOT NULL
                        )';
                WHEN SQLSTATE '42S01' DO
                BEGIN
                END
        END
      END
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (21ms) [Parameters=[], CommandType='Text', CommandTimeout='0']
      EXECUTE BLOCK
      RETURNS (ROWS_AFFECTED INT)
      AS
      BEGIN
        ROWS_AFFECTED = 1;
        BEGIN
                INSERT INTO "__EFMigrationsLock" ("Id", "Timestamp") VALUES (1, CAST('2024-12-21 11.42.21.5440' AS TIMESTAMP));
                WHEN SQLSTATE '23000' DO
                BEGIN
                        ROWS_AFFECTED = 0;
                END
        END
        SUSPEND;
      END
Failed executing DbCommand (21ms) [Parameters=[], CommandType='Text', CommandTimeout='0']
EXECUTE BLOCK
RETURNS (ROWS_AFFECTED INT)
AS
BEGIN
        ROWS_AFFECTED = 1;
        BEGIN
                INSERT INTO "__EFMigrationsLock" ("Id", "Timestamp") VALUES (1, CAST('2024-12-21 11.42.21.5440' AS TIMESTAMP));
                WHEN SQLSTATE '23000' DO
                BEGIN
                        ROWS_AFFECTED = 0;
                END
        END
        SUSPEND;
END
FirebirdSql.Data.FirebirdClient.FbException (0x80004005): Invalid time zone region: .21.5440
At block line: 7, col: 3
 ---> FirebirdSql.Data.Common.IscException: Invalid time zone region: .21.5440
At block line: 7, col: 3
   at FirebirdSql.Data.Client.Managed.IResponseExtensions.HandleResponseException(IResponse response)
   at FirebirdSql.Data.Client.Managed.Version10.GdsDatabase.ReadResponse(Int32 operation)
   at FirebirdSql.Data.Client.Managed.Version10.GdsStatement.Fetch()
   at FirebirdSql.Data.FirebirdClient.FbCommand.ExecuteScalar()
   at FirebirdSql.Data.FirebirdClient.FbCommand.ExecuteScalar()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteScalar(RelationalCommandParameterObject parameterObject)
   at FirebirdSql.EntityFrameworkCore.Firebird.Migrations.Internal.FbHistoryRepository.AcquireDatabaseLock()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
```
 
change project to net  core 8 fix this error.

**Comment by mrotteveel** [comment]
You're using Firebird 4 or higher. The syntax for timestamp become more restrictive in Firebird 4 with the introduction of `with time zone` types. Since Firebird 4, the separator between hours, minutes and seconds *must* be a colon (`:`), so you should use:

```sql
CAST('2024-12-21 11:42:21.5440' AS TIMESTAMP)
```

See also [Datetime Literals](https://www.firebirdsql.org/file/documentation/html/en/refdocs/fblangref40/firebird-40-language-reference.html#fblangref40-commons-datetime-literal)

**Comment by mrotteveel** [comment]
I guess the provider generates this; if so, it needs to be fixed to generate the correct syntax.

@cincuranet If this is generated, using `timestamp '...'` is shorter than such cast.

**Comment by rioda78** [comment]
As information i'm using Firebird 5.0.1

**Comment by cincuranet** [comment]
Hmm, looks like dependencies in `FbHistoryRepository` are not correct and wrong literal is generated. I'll look into it.

**Comment by cincuranet** [comment]
@rioda78 I cannot replicate it. Please provide console app that shows the behavior.

**Comment by cincuranet** [comment]
Never mind, I think I found it. Please check the [beta2](https://www.nuget.org/packages/FirebirdSql.EntityFrameworkCore.Firebird/12.0.0-beta2) and report back.

**Comment by rioda78** [comment]
> Never mind, I think I found it. Please check the [beta2](https://www.nuget.org/packages/FirebirdSql.EntityFrameworkCore.Firebird/12.0.0-beta2) and report back.

thanks you. yes i have try several time with FirebirdSql.EntityFrameworkCore.Firebird v 12.0.0-beta2 and it fix it.
thanks you very much
