### ISSUE TITLE
EF Core scaffolding support [DNET798]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/NETProvider#735]
Submitted by: @cincuranet

Jira\_subtask\_inward [DNET663](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET663+in%3Atitle)
Is duplicated by [DNET886](https://github.com/FirebirdSQL/NETProvider/issues?q=DNET886+in%3Atitle)

Votes: 3

Commits: FirebirdSQL/NETProvider@88da531db57e707af96756ae6c7998eb223fe447

**Comment by sealkeen** [comment]
Can you please tell me how to change the connection string
`Scaffold-DbContext "Server=localhost;Database=C:\Program Files\Firebird\Firebird_3_0\examples\empbuild\EMPLOYEE.FDB;user id=SYSDBA;password=password;" EntityFrameworkCore.FirebirdSql -Force -OutputDir Models`

 to avoid setting `WireCrypt = Enabled ` in the firebird.conf file while scaffolding the database?

Although It's in fact working with the WireCrypt = Enabled, But the data won't be encrypted with the current configuration.

**Comment by cincuranet** [comment]
_EntityFrameworkCore.FirebirdSql_ is not a package developed here.

**Comment by sealkeen** [comment]
> _EntityFrameworkCore.FirebirdSql_ is not a package developed here.

Alright, then can you please specify which certain EntityFrameworkCore version one should use with the latest version of _FirebirdSQL.EntityFramework.Firebird_ to be able to Scaffold an existing DB? Which EFCore.Tools version should one also use with EFCore.Design?

Is there a short version of the connection string where most of the parameters are set to a default value or identified at runtime?

**Comment by cincuranet** [comment]
Use latest stable of FirebirdSql.EntityFrameworkCore.Firebird. The Microsoft.EntityFrameworkCore.Xxx packages should be from 5.x. Support for 6.x is not released yet (#1003).

In connection string you want to set at least database/server and username/password. Rest has sensible default values.

**Comment by sealkeen** [comment]
For the following set up: 
- microsoft.entityframeworkcore\5.0.9; firebirdsql.data.firebirdclient\8.5.4; microsoft.entityframeworkcore.design\5.0.9; firebirdsql.entityframeworkcore.firebird\8.5.4; microsoft.entityframeworkcore.tools\5.0.9. 
- server - remote, TCP/IP, Server version - Firebird 2.5, Charset - WIN1251, Dialect - 1. 

scaffold-dbcontext returns "System.InvalidOperationException: Sequence contains no matching element"

**Comment by abdgad** [comment]
Scaffolding currently only works with EF Core 5

**Comment by abdgad** [comment]
Scaffolding currently only works with EF Core 5. Any updates on scaffolding support for EF Core 6 @cincuranet  ?

**Comment by cincuranet** [comment]
@sealkeen> Dialect 1 might be a problem. It's basically deprecated in server anyway. FB 2.5 is supported by a contribution, but it's not actively maintained (and 2.5 is also EOL), 3.0 is the lowest version tested.

@abdgad> It's done (#1003), but not yet released in RTM. You can try [alpha](https://www.nuget.org/packages/FirebirdSql.Data.FirebirdClient/9.0.0-alpha2) version.

**Comment by Kaster** [comment]
Hello,
what is the current status?

I have following and try to scaffold ...

- Firebird 2.5 
- .NET 6 
- EF Core 6.0.5 
- FirebirdSql.Data.FirebirdClient 9.0.1 
- FirebirdSql.EntityFrameworkCore.Firebird 9.0.1

1. By simple database X (with only 2 tables) I have successful generation of Context class and Entity classes 
2. By same database X with using of flag "Table" I have successful generation only  of context class and not entity class
3. By other (old and complex) database Y, I have no success with generation and have following error:
System.InvalidCastException: Object cannot be cast from DBNull to other types.
   at System.DBNull.System.IConvertible.ToInt32(IFormatProvider provider)
   at System.Convert.ToInt32(Object value, IFormatProvider provider)
   at FirebirdSql.Data.Common.DbValue.GetInt32()
   at FirebirdSql.Data.FirebirdClient.FbDataReader.GetFieldValue[T](Int32 i)
   at FirebirdSql.Data.FirebirdClient.FbDataReader.GetInt32(Int32 i)
   at FirebirdSql.EntityFrameworkCore.Firebird.Scaffolding.Internal.FbDatabaseModelFactory.GetTables(DbConnection connection, Func`3 filter)
   at FirebirdSql.EntityFrameworkCore.Firebird.Scaffolding.Internal.FbDatabaseModelFactory.Create(DbConnection connection, DatabaseModelFactoryOptions options)
   at FirebirdSql.EntityFrameworkCore.Firebird.Scaffolding.Internal.FbDatabaseModelFactory.Create(String connectionString, DatabaseModelFactoryOptions options)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String outputContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluralize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluarlize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Object cannot be cast from DBNull to other types.

And, I can't get any information from the logs about the exact table(s) where the error occurred.

What can I do now?


Thanks!

**Comment by sealkeen** [comment]
> Hello, what is the current status?
> 
> I have following and try to scaffold ...
> 
> * Firebird 2.5
> * .NET 6
> * EF Core 6.0.5
> * FirebirdSql.Data.FirebirdClient 9.0.1
> * FirebirdSql.EntityFrameworkCore.Firebird 9.0.1
> ...
> Thanks!

@Kaster, I ended up using FirebirdSql.Data.FirebirdClient, Version=8.0.1.0 without scaffolding.
That's much less errorsome, although you will nedd to learn some SQL:

```C#
        public static int ExecuteFirebirdProcedure(Action<string> log)
        {
            try
            {
                string conString = "character set=WIN1251;data source=127.0.0.1;initial catalog=database_name;user " +
                "id=SYSDBA;password=masterkey;no garbage collect=true;role name = R201; max pool size" +
                "=1000";
                using (FbConnection FBCon = new FbConnection(conString))
                {
                    FBCon.Open();
                    string param1 = "10.5", param2 = "5.1", param3 = "1.2";
                    FbCommand cmd =
                        new FbCommand($"execute procedure SP$STORED_PROCEDURE('{param1}', '{param2}', '{param3}');", FBCon);
                    int res = cmd.ExecuteNonQuery();
                    FBCon.Close();
                    return res;
                }
            }
            catch (Exception ex)
            {
                log?.Invoke($"{nameof(ExecuteFirebirdProcedure)}: {ex.ToString()}. {ex.Message}");
                return 0;
            }
        }
```

**Comment by Kaster** [comment]
@sealkeen I actually wanted to save myself this trip :-( I have more than 100 tables with an average of 30 columns each.

In the meantime I have updated Firebird to 3.0 ... again there are errors with scaffolding:
`
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at FirebirdSql.EntityFrameworkCore.Firebird.Scaffolding.Internal.FbDatabaseModelFactory.GetIndexes(DbConnection connection, IReadOnlyList`1 tables, Func`3 tableFilter)
   at FirebirdSql.EntityFrameworkCore.Firebird.Scaffolding.Internal.FbDatabaseModelFactory.GetTables(DbConnection connection, Func`3 filter)
   at FirebirdSql.EntityFrameworkCore.Firebird.Scaffolding.Internal.FbDatabaseModelFactory.Create(DbConnection connection, DatabaseModelFactoryOptions options)
   at FirebirdSql.EntityFrameworkCore.Firebird.Scaffolding.Internal.FbDatabaseModelFactory.Create(String connectionString, DatabaseModelFactoryOptions options)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String outputContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluralize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluarlize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
`
But the classic way remains as an alternative.

**Comment by cincuranet** [comment]
@Kaster 
> What can I do now?

Open a new issue and provide the database structure.

**Comment by sealkeen** [comment]
> @sealkeen Thanks for the effort! I actually wanted to save myself this trip :-( I have more than 100 tables with an average of 30 columns each.
> ...

I actually had to deal with more than 1700 tables and 2300+ stored procedures within a single dialect 1 DB, which was larger than a single 220 GB file and I figured out that it's easier to learn SQL, PL/SQL rather than to scaffold it...
