### ISSUE TITLE
Scaffolding with dotnet core 5.0 with error SQL error code = -206 Column unknown

### ISSUE THREAD

**Issue by gitNemo** [FirebirdSQL/NETProvider#955]
Hello

I have a legacy database with uppercased tables names, when I try to scaffold it with entity framework 5.0 with this command:
`dotnet ef dbcontext scaffold "Datasource=192.168.1.110;User=SYSDBA;Password=masterkey;Database=192.168.1.110:C:\Path\To\Database\File.GDB;ServerType=Default;Charset=NONE" firebirdsql.entityframeworkcore.firebird`

I get this error:

```
FirebirdSql.Data.FirebirdClient.FbException (0x80004005): Dynamic SQL Error
SQL error code = -206
Column unknown
R.RDB$RELATION_TYPE
At line 4, column 19
 ---> FirebirdSql.Data.Common.IscException: Dynamic SQL Error
SQL error code = -206
Column unknown
R.RDB$RELATION_TYPE
At line 4, column 19
   at FirebirdSql.Data.Client.Managed.GdsConnection.ProcessResponse(IResponse response)
   at FirebirdSql.Data.Client.Managed.Version10.GdsDatabase.ReadResponse(AsyncWrappingCommonArgs async)
   at FirebirdSql.Data.Client.Managed.Version11.GdsStatement.Prepare(String commandText, AsyncWrappingCommonArgs async)
   at FirebirdSql.Data.Client.Managed.Version11.GdsStatement.Prepare(String commandText, AsyncWrappingCommonArgs async)
   at FirebirdSql.Data.FirebirdClient.FbCommand.Prepare(Boolean returnsSet, AsyncWrappingCommonArgs async)
   at FirebirdSql.Data.FirebirdClient.FbCommand.Prepare(Boolean returnsSet, AsyncWrappingCommonArgs async)
   at FirebirdSql.Data.FirebirdClient.FbCommand.ExecuteCommand(CommandBehavior behavior, Boolean returnsSet, AsyncWrappingCommonArgs async)
   at FirebirdSql.Data.FirebirdClient.FbCommand.ExecuteReaderImpl(CommandBehavior behavior, AsyncWrappingCommonArgs async)
   at FirebirdSql.Data.FirebirdClient.FbCommand.ExecuteReaderImpl(CommandBehavior behavior, AsyncWrappingCommonArgs async)
   at FirebirdSql.Data.FirebirdClient.FbCommand.ExecuteReader(CommandBehavior behavior)
   at FirebirdSql.Data.FirebirdClient.FbCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at FirebirdSql.EntityFrameworkCore.Firebird.Scaffolding.Internal.FbDatabaseModelFactory.GetTables(DbConnection connection, Func`3 filter)
   at FirebirdSql.EntityFrameworkCore.Firebird.Scaffolding.Internal.FbDatabaseModelFactory.Create(DbConnection connection, DatabaseModelFactoryOptions options)
   at FirebirdSql.EntityFrameworkCore.Firebird.Scaffolding.Internal.FbDatabaseModelFactory.Create(String connectionString, DatabaseModelFactoryOptions options)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String outputContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluralize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluarlize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Dynamic SQL Error
SQL error code = -206
Column unknown
R.RDB$RELATION_TYPE
At line 4, column 19
```

**Comment by cincuranet** [comment]
What Firebird version are you using?

**Comment by gitNemo** [comment]
> What Firebird version are you using?

I use Firebird 2.5

**Comment by cincuranet** [comment]
You need to use at least 3.0 for EF Core.

**Comment by gitNemo** [comment]
> You need to use at least 3.0 for EF Core.

I have just installed the 3.0 version, and now I get this error:
```
unsupported on-disk structure for file C:\Path\To\Database\File.GDB; found 10.1, support 12.2
IProvider::attachDatabase failed when loading mapping cache
```

**Comment by cincuranet** [comment]
This a support question. I suggest taking it into firebird-support list/forum.

**Comment by gitNemo** [comment]
> This a support question. I suggest taking it into firebird-support list/forum.

Okey, I will do it. 
Thank you for your patience.
