### ISSUE TITLE
`FirebirdSql.Data.Client.Managed.Version10.GdsStatement.Fetch()` throws `System.NullReferenceException`

### ISSUE THREAD

**Issue by oshinyil** [FirebirdSQL/NETProvider#964]
Hi, 

I got this error in production. I don't know how to reproduce it and what caused it.

```
An exception occurred while iterating over the results of a query for context type 'HP.Database.HpDatabaseContext'.
System.NullReferenceException: Object reference not set to an instance of an object.
   at FirebirdSql.Data.Client.Managed.Version10.GdsStatement.Fetch()
   at FirebirdSql.Data.FirebirdClient.FbCommand.Fetch()
   at FirebirdSql.Data.FirebirdClient.FbDataReader.Read()
   at System.Data.Common.DbDataReader.ReadAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.<MoveNextAsync>d__17.MoveNext() 
System.NullReferenceException: Object reference not set to an instance of an object.
   at FirebirdSql.Data.Client.Managed.Version10.GdsStatement.Fetch()
   at FirebirdSql.Data.FirebirdClient.FbCommand.Fetch()
   at FirebirdSql.Data.FirebirdClient.FbDataReader.Read()
   at System.Data.Common.DbDataReader.ReadAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.<MoveNextAsync>d__17.MoveNext()
```

`FirebirdSql.EntityFrameworkCore.Firebird` version `7.10.1`

Could you please help to fix this issue?

Thank you.

**Comment by cincuranet** [comment]
A call stack is not enough to understand this issue. Steps to reproduce would be best. But providing _as much information as possible_ what was happening before and what is the environment is a good start.

**Comment by oshinyil** [comment]
Here is the environment.

- `Environment.Version`: `4.0.30319.42000`
- `RuntimeInformation.FrameworkDescription`: `4.7.3740.0`
- `RuntimeInformation.OSDescription`: `Microsoft Windows 10.0.17763`

I am not sure what was happening before. The error suddenly happened and we needed to restart the application.

**Comment by cincuranet** [comment]
Closing in favor of #963.
