### ISSUE TITLE
Scaffold-DbContext --- FirebirdSql.Data.FirebirdClient.FbException (0x80004005): Dynamic SQL Error

### ISSUE THREAD

**Issue by WalterGoy** [FirebirdSQL/NETProvider#970]
Hi Folks,
My objective is to, as simply as possible, use Firebird Entity Framework (EF) data provider to exercise EF data base first ORM i.e. use Visual Studio Package Manager Console’s (PMC) command, Scaffold-DbContext. When I try that I get an exception. Very grateful if I could get info. on what I’m doing wrong?
Details of my setup are: -
a)	Microsoft Visual Studio Community 2019 --- Ver. 16.10.1
b)	Firebird DB server --- Ver. 8.0.1
c)	Data Base (DB) --- example DB provided with Firebird install, employee.fdb
d)	Firebird DB Data Provider --- FirebirdSql.EntityFrameworkCore.Firebird, Ver. 8.0.1
e)	Microsoft EF packages used
- Microsoft.EntityFrameworkCore, Ver. 5.0.8
- Microsoft.EntityFrameworkCore.Toools, Ver. 5.0.8
- Microsoft.EntityFrameworkCore.Design, Ver. 5.0.8

f)	See below for my PCM command & resulting PCM output. Note the listing below we can see “**No referenced design-time services were found**”. Does FirebirdSql.EntityFrameworkCore.Firebird actually support the PMC’s Scaffold-DbContext command?
--------------------------------------------- PMC listing ---------------------------------------------------------------------
PM> Scaffold-DbContext "User ID=sysdba; Password=masterkey; Database=localhost:C:\\Program Files\\Firebird\\Firebird_2_5\\examples\\empbuild\\employee.fdb; DataSource=localhost; Charset=NONE;" FirebirdSql.EntityFrameworkCore.Firebird -verbose
Using project 'TestFbEfDataProvider'.
Using startup project 'TestFbEfDataProvider'.
Build started...
Build succeeded.
C:\Program Files\dotnet\dotnet.exe exec --depsfile E:\WGoyd_000\Code\Databases\FireBird\TestFbEfDataProvider\TestFbEfDataProvider\bin\Debug\net5.0\TestFbEfDataProvider.deps.json --additionalprobingpath C:\Users\WGoyd_000\.nuget\packages --additionalprobingpath "C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages" --additionalprobingpath "C:\Program Files (x86)\Microsoft\Xamarin\NuGet" --additionalprobingpath "C:\Program Files\dotnet\sdk\NuGetFallbackFolder" --runtimeconfig E:\WGoyd_000\Code\Databases\FireBird\TestFbEfDataProvider\TestFbEfDataProvider\bin\Debug\net5.0\TestFbEfDataProvider.runtimeconfig.json C:\Users\WGoyd_000\.nuget\packages\microsoft.entityframeworkcore.tools\5.0.8\tools\netcoreapp2.0\any\ef.dll dbcontext scaffold "User ID=sysdba; Password=masterkey; Database=localhost:C:\\\\Program Files\\\\Firebird\\\\Firebird_2_5\\\\examples\\\\empbuild\\\\employee.fdb; DataSource=localhost; Charset=NONE;" FirebirdSql.EntityFrameworkCore.Firebird --json --verbose --no-color --prefix-output --assembly E:\WGoyd_000\Code\Databases\FireBird\TestFbEfDataProvider\TestFbEfDataProvider\bin\Debug\net5.0\TestFbEfDataProvider.dll --startup-assembly E:\WGoyd_000\Code\Databases\FireBird\TestFbEfDataProvider\TestFbEfDataProvider\bin\Debug\net5.0\TestFbEfDataProvider.dll --project-dir E:\WGoyd_000\Code\Databases\FireBird\TestFbEfDataProvider\TestFbEfDataProvider\ --language C# --working-dir E:\WGoyd_000\Code\Databases\FireBird\TestFbEfDataProvider --root-namespace TestFbEfDataProvider
Using assembly 'TestFbEfDataProvider'.
Using startup assembly 'TestFbEfDataProvider'.
Using application base 'E:\WGoyd_000\Code\Databases\FireBird\TestFbEfDataProvider\TestFbEfDataProvider\bin\Debug\net5.0'.
Using working directory 'E:\WGoyd_000\Code\Databases\FireBird\TestFbEfDataProvider\TestFbEfDataProvider'.
Using root namespace 'TestFbEfDataProvider'.
Using project directory 'E:\WGoyd_000\Code\Databases\FireBird\TestFbEfDataProvider\TestFbEfDataProvider\'.
Remaining arguments: .
Finding design-time services for provider 'FirebirdSql.EntityFrameworkCore.Firebird'...
Using design-time services from provider 'FirebirdSql.EntityFrameworkCore.Firebird'.
Finding design-time services referenced by assembly 'TestFbEfDataProvider'...
Finding design-time services referenced by assembly 'TestFbEfDataProvider'...
No referenced design-time services were found.
Finding IDesignTimeServices implementations in assembly 'TestFbEfDataProvider'...
No design-time services were found.
To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
FirebirdSql.Data.FirebirdClient.FbException (0x80004005): Dynamic SQL Error
SQL error code = -206
Column unknown
RF.RDB$IDENTITY_TYPE
At line 35, column 28
 ---> FirebirdSql.Data.Common.IscException: Dynamic SQL Error
SQL error code = -206
Column unknown
RF.RDB$IDENTITY_TYPE
At line 35, column 28
   at FirebirdSql.Data.Client.Managed.GdsConnection.ProcessResponse(IResponse response)
   at FirebirdSql.Data.Client.Managed.Version10.GdsDatabase.ReadResponse(AsyncWrappingCommonArgs async)
   at FirebirdSql.Data.Client.Managed.Version11.GdsStatement.Prepare(String commandText, AsyncWrappingCommonArgs async)
   at FirebirdSql.Data.Client.Managed.Version11.GdsStatement.Prepare(String commandText, AsyncWrappingCommonArgs async)
   at FirebirdSql.Data.FirebirdClient.FbCommand.Prepare(Boolean returnsSet, AsyncWrappingCommonArgs async)
   at FirebirdSql.Data.FirebirdClient.FbCommand.Prepare(Boolean returnsSet, AsyncWrappingCommonArgs async)
   at FirebirdSql.Data.FirebirdClient.FbCommand.ExecuteCommand(CommandBehavior behavior, Boolean returnsSet, AsyncWrappingCommonArgs async)
   at FirebirdSql.Data.FirebirdClient.FbCommand.ExecuteReaderImpl(CommandBehavior behavior, AsyncWrappingCommonArgs async)
   at FirebirdSql.Data.FirebirdClient.FbCommand.ExecuteReaderImpl(CommandBehavior behavior, AsyncWrappingCommonArgs async)
   at FirebirdSql.Data.FirebirdClient.FbCommand.ExecuteReader(CommandBehavior behavior)
   at FirebirdSql.Data.FirebirdClient.FbCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at FirebirdSql.EntityFrameworkCore.Firebird.Scaffolding.Internal.FbDatabaseModelFactory.GetColumns(DbConnection connection, IReadOnlyList`1 tables, Func`3 tableFilter)
   at FirebirdSql.EntityFrameworkCore.Firebird.Scaffolding.Internal.FbDatabaseModelFactory.GetTables(DbConnection connection, Func`3 filter)
   at FirebirdSql.EntityFrameworkCore.Firebird.Scaffolding.Internal.FbDatabaseModelFactory.Create(DbConnection connection, DatabaseModelFactoryOptions options)
   at FirebirdSql.EntityFrameworkCore.Firebird.Scaffolding.Internal.FbDatabaseModelFactory.Create(String connectionString, DatabaseModelFactoryOptions options)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String outputContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluralize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluarlize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Dynamic SQL Error
SQL error code = -206
Column unknown
RF.RDB$IDENTITY_TYPE
At line 35, column 28
PM>

**Comment by cincuranet** [comment]
The error you see is because you use FB2.5. That old and unsupported version for EF Core. You need to use at least FB3.

**Comment by WalterGoy** [comment]
Thanks so much for resolving this issue for me!
My real app. will target a FireBird server that is still running this old version, very sad! The GOOD NEWS is **_FirebirdSql.Data.FirebirdClient_** seems to work just fine!
