### ISSUE TITLE
Getting Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.1 .. when using FB Client 8.0.1 on .NET 4.8

### ISSUE THREAD

**Issue by FransBouma** [FirebirdSQL/NETProvider#971]
Hi,

I get the following exception:
```
Exception message:
-------------------------------
Exception type: FbException
Error writing data to the connection.
Error reading data from the connection.

Inner exception message:
-------------------------------
Exception type: FbException
Error writing data to the connection.
Error reading data from the connection.

Inner exception message:
-------------------------------
Exception type: IscException
Error writing data to the connection.
Error reading data from the connection.

Inner exception message:
-------------------------------
Exception type: FileNotFoundException
Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
```

Stacktrace:
```
LLBLGen Pro version 5.9. Build 5.9.21.0512
-----[Core exception]--------------------
   at FirebirdSql.Data.Schema.FbSchema.<GetSchema>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at FirebirdSql.Data.Schema.FbSchema.<GetSchema>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FirebirdSql.Data.FirebirdClient.FbConnection.GetSchema(String collectionName, String[] restrictions)
   at SD.LLBLGen.Pro.DBDrivers.Firebird.FirebirdDBDriver.GetAllElementNames(String schemaCollectionName, String[] restrictions, String nameFieldName) in C:\MyProjects\VS.NET Projects\LLBLGen Pro v5.9\Drivers\Firebird\FirebirdDBDriver.cs:line 530
   at SD.LLBLGen.Pro.DBDrivers.Firebird.FirebirdDBDriver.GetAllTableNames(String catalogName, String schemaName) in C:\MyProjects\VS.NET Projects\LLBLGen Pro v5.9\Drivers\Firebird\FirebirdDBDriver.cs:line 405
   at SD.LLBLGen.Pro.Gui.Controls.WizardPages.MetaDataRetrievalWizard_Step_ElementSelection.PopulateSchema(TreeListNode schemaNodeToPopulate, TagEntry`1 tagData) in C:\MyProjects\VS.NET Projects\LLBLGen Pro v5.9\Designer\Gui\Controls\WizardPages\MetaDataRetrievalWizard_Step_ElementSelection.cs:line 458
-----[InnerException]--------------------
   at FirebirdSql.Data.FirebirdClient.FbCommand.<ExecuteReaderImpl>d__89.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FirebirdSql.Data.FirebirdClient.FbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at FirebirdSql.Data.Schema.FbSchema.<GetSchema>d__1.MoveNext()
-----[InnerException]--------------------
   at FirebirdSql.Data.Client.Managed.Version12.GdsStatement.<Execute>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FirebirdSql.Data.FirebirdClient.FbCommand.<ExecuteCommand>d__119.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FirebirdSql.Data.FirebirdClient.FbCommand.<ExecuteReaderImpl>d__89.MoveNext()
-----[InnerException]--------------------
   at FirebirdSql.Data.Client.Managed.Version13.GdsStatement.WriteParameters(AsyncWrappingCommonArgs async)
   at FirebirdSql.Data.Client.Managed.Version10.GdsStatement.<SendExecuteToBuffer>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FirebirdSql.Data.Client.Managed.Version12.GdsStatement.<Execute>d__2.MoveNext()
```

When running it on .net 4.8 (.net 4.7.x gave the same issue), when trying to obtain a schema. I load the provider via the DbProviderFactories registered factory. I try to obtain the schema of the default Employee.fdb database. 
Errors too on llblgen pro v5.8 so it's not some new code I added for FB4 that gives this issue. Funny thing is if I ignore the exception and proceed, it'll pull the schema properly from the DB. I use charset NONE. 

Any ideas what it could be other than a missing reference that I don't think I need ? 

(When I do add the System.Threading.Tasks.Extensions nuget package I get the same error, so it's an additional assembly)

**Comment by cincuranet** [comment]
> Any ideas what it could be other than a missing reference that I don't think I need ?

You need `System.Threading.Tasks.Extensions` package ([here's the reference](https://github.com/FirebirdSQL/NETProvider/blob/master/Provider/src/FirebirdSql.Data.FirebirdClient/FirebirdSql.Data.FirebirdClient.csproj#L41)). 

> (When I do add the System.Threading.Tasks.Extensions nuget package I get the same error, so it's an additional assembly)

Is it a correct version? Are transitive dependencies available? Something interesting in _fusion log_?

**Comment by FransBouma** [comment]
> 
> 
> > Any ideas what it could be other than a missing reference that I don't think I need ?
> 
> You need `System.Threading.Tasks.Extensions` package ([here's the reference](https://github.com/FirebirdSQL/NETProvider/blob/master/Provider/src/FirebirdSql.Data.FirebirdClient/FirebirdSql.Data.FirebirdClient.csproj#L41)).

But that means that all my drivers of all older versions can't use FB Client v8.0.1, as none of them reference System.Threading.Tasks.Extensions. It's the old days all over again, while I pull the factory for the provider from the DbProviderFactories. 

> 
> > (When I do add the System.Threading.Tasks.Extensions nuget package I get the same error, so it's an additional assembly)
> 
> Is it a correct version? Are transitive dependencies available? Something interesting in _fusion log_?

I referenced the latest version from nuget. It has 1 dependency, which is also referenced. 

Fusion says:
```
*** Assembly Binder Log Entry  (19/07/2021 @ 14:30:38) ***

The operation failed.
Bind result: hr = 0x80070002. The system cannot find the file specified.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Running under executable  C:\MyProjects\VS.NET Projects\LLBLGen Pro v5.8\Designer\Gui\bin\Debug\LLBLGenPro.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = System.Threading.Tasks.Extensions, Version=4.2.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
 (Fully-specified)
LOG: Appbase = file:///C:/MyProjects/VS.NET Projects/LLBLGen Pro v5.8/Designer/Gui/bin/Debug/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = LLBLGenPro.exe
Calling assembly : FirebirdSql.Data.FirebirdClient, Version=8.0.1.0, Culture=neutral, PublicKeyToken=3750abcc3150b00c.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\MyProjects\VS.NET Projects\LLBLGen Pro v5.8\Designer\Gui\bin\Debug\LLBLGenPro.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: The same bind was seen before, and was failed with hr = 0x80070002.
ERR: Unrecoverable error occurred during pre-download check (hr = 0x80070002).
```

Folder contents:
![image](https://user-images.githubusercontent.com/3628530/126160255-0d621269-128f-41af-b14a-0029ebdfa932.png)

And this is in the probing path.

**Comment by FransBouma** [comment]
**FOUND IT**
PEBKAC: the assemblies were in the driver output folder, but not copied correctly to the real execution folder and the probing path looked *there* and not in this folder. 
Closed, sorry for wasting your time. 

Still a problematic issue however for older releases who use FB Client 8.0.1 now as they will run into this issue 100%.

**Comment by cincuranet** [comment]
Glad you solved it.

BTW, given this dependency is new in new major version, can't you reject in previous versions version 8+ (which would be simple change)? And when somebody wants new(er) version of _FirebirdClient_ (s)he also needs to update LLBLGen's driver(s)?

**Comment by FransBouma** [comment]
I can't update all older versions, 2 are under support (5.7 and 5.8) and for years people would be able to upgrade their ado.net provider and it would work (as dbproviderfactories solved that). Users who now do that will run into this issue which is unexpected. 

It's not that hard to fix, copying two assemblies to the driver folder will make it work (or they should keep using an older firebird client library), it might be annoying for the users who run into this. What I wanted to avoid is to have to take a dependency on an ADO.NET provider myself, but I have to do that now. It's not the end of the world, it was inevitable anyway considering everyone moving to .net core so ado.net providers move to nuget package installations only anyway. 

In any case I now know why this happens and if someone runs into this, how to suggest they fix it :)
